apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-scale-set
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://actions-runner-controller.github.io/actions-runner-controller
      chart: gha-runner-scale-set
      targetRevision: 0.9.3
      helm:
        valueFiles:
          - $values/arc-scale-set/values.yaml
    - repoURL: https://github.com/taronaeo/runner-cd.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
